#!/bin/sh

# Test vtsl

. ./testlib

cleanup(){
   [ "$TMP" != "" ] && rm -f $TMP.test10*
}

vtgen -a0 -n a=0.1 -r48000 -T2010-01-01,+5 $TMP.test10a,f8
vtsl -r -n 56789 $TMP.test10b,f8 2> /dev/null &
sleep 1
vtsl -s -n localhost,56789 $TMP.test10a 2> /dev/null
sleep 1
cor=`vtjoin $TMP.test10a $TMP.test10b - | vtcmp -mcor -w0.1 |
       awk '($1+0 == 0){ printf( "%.3f", $2) }'`
test "$cor" = "1.000"
result "t1a"

vtgen -a0 -n a=0.1 -r48000 -T2010-01-01,+5 $TMP.test10a,f4
vtsl -r -n 56789 $TMP.test10b,f4 2> /dev/null &
sleep 1
vtsl -s -n localhost,56789 $TMP.test10a 2> /dev/null
sleep 1
cor=`vtjoin $TMP.test10a $TMP.test10b - | vtcmp -mcor -w0.1 |
       awk '($1+0 == 0){ printf( "%.3f", $2) }'`
test "$cor" = "1.000"
result "t1b"

vtgen -a0 -n a=0.1 -r48000 -T2010-01-01,+5 $TMP.test10a,i4
vtsl -r -n 56789 $TMP.test10b,i4 2> /dev/null &
sleep 1
vtsl -s -n localhost,56789 $TMP.test10a 2> /dev/null
sleep 1
cor=`vtjoin $TMP.test10a $TMP.test10b - | vtcmp -mcor -w0.1 |
       awk '($1+0 == 0){ printf( "%.3f", $2) }'`
test "$cor" = "1.000"
result "t1c"

vtgen -a0 -n a=0.1 -r48000 -T2010-01-01,+5 $TMP.test10a,i2
vtsl -r -n 56789 $TMP.test10b,i2 2> /dev/null &
sleep 1
vtsl -s -n localhost,56789 $TMP.test10a 2> /dev/null
sleep 1
cor=`vtjoin $TMP.test10a $TMP.test10b - | vtcmp -mcor -w0.1 |
       awk '($1+0 == 0){ printf( "%.3f", $2) }'`
test "$cor" = "1.000"
result "t1d"

vtgen -a0 -n a=0.1 -r48000 -T2010-01-01,+5 $TMP.test10a
vtgen -a0 -s a=0.1,f=400 -r48000 -T2010-01-01,+5 $TMP.test10b
vtjoin $TMP.test10a $TMP.test10b $TMP.test10c,f8
vtsl -r -n 56789 $TMP.test10d,f8 2> /dev/null &
sleep 1
vtsl -s -n localhost,56789 $TMP.test10c 2> /dev/null
sleep 1
cor=`vtjoin $TMP.test10c $TMP.test10d - | vtcmp -mcor -w0.1 -- -:1,3  |
       awk '($1+0 == 0){ printf( "%.3f", $2) }'`
test "$cor" = "1.000"
result "t2a"
cor=`vtjoin $TMP.test10c $TMP.test10d - | vtcmp -mcor -w0.1 -- -:2,4  |
       awk '($1+0 == 0){ printf( "%.3f", $2) }'`
test "$cor" = "1.000"
result "t2b"

cleanup
